-- Enable Row Level Security (RLS)
-- This ensures users can only see their own data

-- 1. PROFILES TABLE (Linked to Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;

create policy "Users can view their own profile." 
  on profiles for select using (auth.uid() = id);

create policy "Users can update their own profile." 
  on profiles for update using (auth.uid() = id);

-- Function to handle new user signup automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. WORKFLOWS TABLE (The Studio Data)
create table workflows (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  description text,
  department text check (department in ('Sales', 'Marketing', 'HR', 'Finance', 'Operations', 'Executive', 'IT/Eng')),
  category text check (category in ('hitl', 'triggered', 'background')),
  trigger_event text,
  action_chain text,
  tools text[], -- Array of strings e.g. ['Gmail', 'Slack']
  
  -- Visual Properties for the "Book Spine"
  color_theme text, 
  spine_height integer default 28,

  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table workflows enable row level security;

-- RLS Policies for Workflows
create policy "Users can view their own workflows." 
  on workflows for select using (auth.uid() = user_id);

create policy "Users can insert their own workflows." 
  on workflows for insert with check (auth.uid() = user_id);

create policy "Users can update their own workflows." 
  on workflows for update using (auth.uid() = user_id);

create policy "Users can delete their own workflows." 
  on workflows for delete using (auth.uid() = user_id);
